# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SVI_HMM <- function(Data_sequence, sub_lengthh, KK, W_AA, uu, kk, sigma, vv, U_AA, U_phi11, U_phi22, U_phi3, U_phi44, Dimm, Passs, pree) {
    .Call('_SVI_SVI_HMM', PACKAGE = 'SVI', Data_sequence, sub_lengthh, KK, W_AA, uu, kk, sigma, vv, U_AA, U_phi11, U_phi22, U_phi3, U_phi44, Dimm, Passs, pree)
}

SVI_LDA <- function(X, KK, nn, alphaa, etaa, pree, word_lengthh) {
    .Call('_SVI_SVI_LDA', PACKAGE = 'SVI', X, KK, nn, alphaa, etaa, pree, word_lengthh)
}

rcpparma_hello_world <- function() {
    .Call('_SVI_rcpparma_hello_world', PACKAGE = 'SVI')
}

rcpparma_outerproduct <- function(x) {
    .Call('_SVI_rcpparma_outerproduct', PACKAGE = 'SVI', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_SVI_rcpparma_innerproduct', PACKAGE = 'SVI', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_SVI_rcpparma_bothproducts', PACKAGE = 'SVI', x)
}

